# ...existing code...
INSTALLED_APPS = [
    # ...existing code...
    'corsheaders',
    # ...existing code...
]

MIDDLEWARE = [
    # ...existing code...
    'corsheaders.middleware.CorsMiddleware',
    # ...existing code...
]

CORS_ALLOW_ALL_ORIGINS = True  # Allow all origins for simplicity, adjust as needed
# ...existing code...
